#!/bin/bash

set -euo pipefail

cd example/init

go get github.com/swiftcarrot/gqlgen

if { go run github.com/swiftcarrot/gqlgen init 2>&1 >&3 3>&- | grep '^' >&2; } 3>&1; then
    echo "gqlgen init failed validation"
    exit 125
fi
